### PR TITLE
Vector base register fixed for 68010+ systems

### LINKED ISSUE #78: Read VBR while taking over OS
I've found such code [here](http://eab.abime.net/showthread.php?t=65430&page=3)

``` c
static APTR GetVBR(void)
{
	APTR vbr = NULL;
	UWORD getvbr[] = {0x4e7a, 0x0801, 0x4e73}; // MOVEC.L VBR,D0 RTE

	if (SysBase->AttnFlags & AFF_68010)
		vbr = (APTR)Supervisor((void *)getvbr);

	return vbr;
}
```

### PR DESCRIPTION
**Pull request by Ozzyboshi**
With this commit interrupts are working on  68010+ systems which don't have VBR at zero.
Code was taken from issue #78 and tested on vampire v600 + coffin r52.
This commit closes #78 hopefully.

### CODE REVIEW

File: src/ace/managers/system.c [hunk 1]
```diff
@@ -300,7 +302,11 @@ void systemCreate(void) {
 	WaitTOF(); // Wait for interlaced screen to finish
 
 	// get VBR location on 68010+ machine
-	// TODO VBR
+	if (SysBase->AttnFlags & AFF_68010)
+	{
```
Comment (tehKaiN) [inline src/ace/managers/system.c]: Brace is not codestyle compliant - move it past `if` condition bracket in same line

File: src/ace/managers/system.c [hunk 2]
```diff
@@ -300,7 +302,11 @@ void systemCreate(void) {
...
+		UWORD getvbr[] = {0x4e7a, 0x0801, 0x4e73};
```
Comment (tehKaiN) [inline src/ace/managers/system.c]: change `getvbr` name to something codestyle compliant - p since it's a pointer (array but it's virtually the same), so perhaps something like `pGetVbrCode`?
